# Generated by Django 5.0.2 on 2024-03-17 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='polyPoints',
            field=models.IntegerField(default=0),
        ),
    ]
