# Generated by Django 5.0.2 on 2024-03-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_polypoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='icon',
            field=models.CharField(default='spade', max_length=50),
        ),
    ]
